/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type {
  Signer,
  AddressLike,
  ContractDeployTransaction,
  ContractRunner,
} from "ethers";
import type { NonPayableOverrides } from "../common";
import type { TreasuryMock, TreasuryMockInterface } from "../TreasuryMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "dao_",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "newDAO",
        type: "address",
      },
    ],
    name: "DAOUpdated",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "memo",
        type: "string",
      },
    ],
    name: "Deposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: true,
        internalType: "bytes32",
        name: "proposalHash",
        type: "bytes32",
      },
    ],
    name: "WithdrawalRequested",
    type: "event",
  },
  {
    inputs: [],
    name: "dao",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "newDAO",
        type: "address",
      },
    ],
    name: "setDAO",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "proposalHash",
        type: "bytes32",
      },
    ],
    name: "withdraw",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x60803461007457601f6102dc38819003918201601f19168301916001600160401b038311848410176100795780849260209460405283398101031261007457516001600160a01b0381169081900361007457600080546001600160a01b03191691909117905560405161024c90816100908239f35b600080fd5b634e487b7160e01b600052604160045260246000fdfe6040608081526004361015610062575b361561001a57600080fd5b6006815191348352806020840152820152656e617469766560d01b60608201527f643e927b32d5bfd08eccd2fcbd97057ad413850f857a2359639114e8e8dd3d7b60803392a2005b6000803560e01c8063106e62901461016b5780634162169f146101435763e73a914c1461008f575061000f565b903461013f57602036600319011261013f576001600160a01b03600435818116929083900361013b576100c7845492831633146101d5565b821561010357506001600160a01b031916811782557f395c0f5a57accc3f0c20646b402f0845c448f3e4ac4a2ec56a3eaf26d15bf79a8280a280f35b5162461bcd60e51b815260206004820152601260248201527154726561737572793a2044414f207a65726f60701b6044820152606490fd5b8380fd5b5080fd5b50903461013f578160031936011261013f57905490516001600160a01b039091168152602090f35b50903461013f57606036600319011261013f576004356001600160a01b03818116929183900361013b576101a39084541633146101d5565b519060243582527f4c7560ade96539004d62355a0c96b508c1787ea0839d9cd4c69940a80f587bf9602060443593a380f35b156101dc57565b60405162461bcd60e51b815260206004820152601260248201527154726561737572793a2044414f206f6e6c7960701b6044820152606490fdfea264697066735822122010c5e8610bb3f645e693ceb8a41d888e9ec50478199f35c136978b430991f78364736f6c63430008170033";

type TreasuryMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TreasuryMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TreasuryMock__factory extends ContractFactory {
  constructor(...args: TreasuryMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    dao_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(dao_, overrides || {});
  }
  override deploy(
    dao_: AddressLike,
    overrides?: NonPayableOverrides & { from?: string }
  ) {
    return super.deploy(dao_, overrides || {}) as Promise<
      TreasuryMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TreasuryMock__factory {
    return super.connect(runner) as TreasuryMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TreasuryMockInterface {
    return new Interface(_abi) as TreasuryMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TreasuryMock {
    return new Contract(address, _abi, runner) as unknown as TreasuryMock;
  }
}
