/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StakingRewards } from "./StakingRewards";
export type { ValidatorRegistry } from "./ValidatorRegistry";
export * as factories from "./factories";
export { StakingRewards__factory } from "./factories/StakingRewards__factory";
export { ValidatorRegistry__factory } from "./factories/ValidatorRegistry__factory";
