/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface StakingRewardsInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "PROOF_INTERVAL"
      | "admin"
      | "baseReward"
      | "deposit"
      | "fundRewardPool"
      | "proofHashUsed"
      | "registry"
      | "rewardManager"
      | "rewardValidator"
      | "setRewardManager"
      | "setRewardParameters"
      | "stakes"
      | "submitProof"
      | "uptimeMultiplier"
      | "withdraw"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProofSubmitted"
      | "RewardManagerUpdated"
      | "RewardParametersUpdated"
      | "RewardPoolFunded"
      | "StakeDeposited"
      | "StakeWithdrawn"
      | "ValidatorRewarded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "PROOF_INTERVAL",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "baseReward",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "deposit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "fundRewardPool",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "proofHashUsed",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "registry", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "rewardManager",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardValidator",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardManager",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setRewardParameters",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "stakes", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "submitProof",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "uptimeMultiplier",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdraw",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "PROOF_INTERVAL",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "baseReward", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "fundRewardPool",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "proofHashUsed",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "registry", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "rewardManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rewardValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardManager",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setRewardParameters",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "stakes", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "uptimeMultiplier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;
}

export namespace ProofSubmittedEvent {
  export type InputTuple = [
    validator: AddressLike,
    proofHash: BytesLike,
    reward: BigNumberish
  ];
  export type OutputTuple = [
    validator: string,
    proofHash: string,
    reward: bigint
  ];
  export interface OutputObject {
    validator: string;
    proofHash: string;
    reward: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardManagerUpdatedEvent {
  export type InputTuple = [rewardManager: AddressLike];
  export type OutputTuple = [rewardManager: string];
  export interface OutputObject {
    rewardManager: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardParametersUpdatedEvent {
  export type InputTuple = [
    baseReward: BigNumberish,
    uptimeMultiplier: BigNumberish
  ];
  export type OutputTuple = [baseReward: bigint, uptimeMultiplier: bigint];
  export interface OutputObject {
    baseReward: bigint;
    uptimeMultiplier: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RewardPoolFundedEvent {
  export type InputTuple = [funder: AddressLike, amount: BigNumberish];
  export type OutputTuple = [funder: string, amount: bigint];
  export interface OutputObject {
    funder: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeDepositedEvent {
  export type InputTuple = [
    validator: AddressLike,
    amount: BigNumberish,
    totalStake: BigNumberish
  ];
  export type OutputTuple = [
    validator: string,
    amount: bigint,
    totalStake: bigint
  ];
  export interface OutputObject {
    validator: string;
    amount: bigint;
    totalStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeWithdrawnEvent {
  export type InputTuple = [
    validator: AddressLike,
    amount: BigNumberish,
    remainingStake: BigNumberish
  ];
  export type OutputTuple = [
    validator: string,
    amount: bigint,
    remainingStake: bigint
  ];
  export interface OutputObject {
    validator: string;
    amount: bigint;
    remainingStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRewardedEvent {
  export type InputTuple = [validator: AddressLike, rewardAmount: BigNumberish];
  export type OutputTuple = [validator: string, rewardAmount: bigint];
  export interface OutputObject {
    validator: string;
    rewardAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface StakingRewards extends BaseContract {
  connect(runner?: ContractRunner | null): StakingRewards;
  waitForDeployment(): Promise<this>;

  interface: StakingRewardsInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  PROOF_INTERVAL: TypedContractMethod<[], [bigint], "view">;

  admin: TypedContractMethod<[], [string], "view">;

  baseReward: TypedContractMethod<[], [bigint], "view">;

  deposit: TypedContractMethod<[], [void], "payable">;

  fundRewardPool: TypedContractMethod<[], [void], "payable">;

  proofHashUsed: TypedContractMethod<[arg0: BytesLike], [boolean], "view">;

  registry: TypedContractMethod<[], [string], "view">;

  rewardManager: TypedContractMethod<[], [string], "view">;

  rewardValidator: TypedContractMethod<
    [validator: AddressLike, rewardAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  setRewardManager: TypedContractMethod<
    [_rewardManager: AddressLike],
    [void],
    "nonpayable"
  >;

  setRewardParameters: TypedContractMethod<
    [_baseReward: BigNumberish, _uptimeMultiplier: BigNumberish],
    [void],
    "nonpayable"
  >;

  stakes: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  submitProof: TypedContractMethod<
    [proofHash: BytesLike],
    [void],
    "nonpayable"
  >;

  uptimeMultiplier: TypedContractMethod<[], [bigint], "view">;

  withdraw: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "PROOF_INTERVAL"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "baseReward"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "fundRewardPool"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "proofHashUsed"
  ): TypedContractMethod<[arg0: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "registry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rewardManager"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "rewardValidator"
  ): TypedContractMethod<
    [validator: AddressLike, rewardAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setRewardManager"
  ): TypedContractMethod<[_rewardManager: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setRewardParameters"
  ): TypedContractMethod<
    [_baseReward: BigNumberish, _uptimeMultiplier: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "stakes"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitProof"
  ): TypedContractMethod<[proofHash: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "uptimeMultiplier"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdraw"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "ProofSubmitted"
  ): TypedContractEvent<
    ProofSubmittedEvent.InputTuple,
    ProofSubmittedEvent.OutputTuple,
    ProofSubmittedEvent.OutputObject
  >;
  getEvent(
    key: "RewardManagerUpdated"
  ): TypedContractEvent<
    RewardManagerUpdatedEvent.InputTuple,
    RewardManagerUpdatedEvent.OutputTuple,
    RewardManagerUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardParametersUpdated"
  ): TypedContractEvent<
    RewardParametersUpdatedEvent.InputTuple,
    RewardParametersUpdatedEvent.OutputTuple,
    RewardParametersUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "RewardPoolFunded"
  ): TypedContractEvent<
    RewardPoolFundedEvent.InputTuple,
    RewardPoolFundedEvent.OutputTuple,
    RewardPoolFundedEvent.OutputObject
  >;
  getEvent(
    key: "StakeDeposited"
  ): TypedContractEvent<
    StakeDepositedEvent.InputTuple,
    StakeDepositedEvent.OutputTuple,
    StakeDepositedEvent.OutputObject
  >;
  getEvent(
    key: "StakeWithdrawn"
  ): TypedContractEvent<
    StakeWithdrawnEvent.InputTuple,
    StakeWithdrawnEvent.OutputTuple,
    StakeWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRewarded"
  ): TypedContractEvent<
    ValidatorRewardedEvent.InputTuple,
    ValidatorRewardedEvent.OutputTuple,
    ValidatorRewardedEvent.OutputObject
  >;

  filters: {
    "ProofSubmitted(address,bytes32,uint256)": TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;
    ProofSubmitted: TypedContractEvent<
      ProofSubmittedEvent.InputTuple,
      ProofSubmittedEvent.OutputTuple,
      ProofSubmittedEvent.OutputObject
    >;

    "RewardManagerUpdated(address)": TypedContractEvent<
      RewardManagerUpdatedEvent.InputTuple,
      RewardManagerUpdatedEvent.OutputTuple,
      RewardManagerUpdatedEvent.OutputObject
    >;
    RewardManagerUpdated: TypedContractEvent<
      RewardManagerUpdatedEvent.InputTuple,
      RewardManagerUpdatedEvent.OutputTuple,
      RewardManagerUpdatedEvent.OutputObject
    >;

    "RewardParametersUpdated(uint256,uint256)": TypedContractEvent<
      RewardParametersUpdatedEvent.InputTuple,
      RewardParametersUpdatedEvent.OutputTuple,
      RewardParametersUpdatedEvent.OutputObject
    >;
    RewardParametersUpdated: TypedContractEvent<
      RewardParametersUpdatedEvent.InputTuple,
      RewardParametersUpdatedEvent.OutputTuple,
      RewardParametersUpdatedEvent.OutputObject
    >;

    "RewardPoolFunded(address,uint256)": TypedContractEvent<
      RewardPoolFundedEvent.InputTuple,
      RewardPoolFundedEvent.OutputTuple,
      RewardPoolFundedEvent.OutputObject
    >;
    RewardPoolFunded: TypedContractEvent<
      RewardPoolFundedEvent.InputTuple,
      RewardPoolFundedEvent.OutputTuple,
      RewardPoolFundedEvent.OutputObject
    >;

    "StakeDeposited(address,uint256,uint256)": TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;
    StakeDeposited: TypedContractEvent<
      StakeDepositedEvent.InputTuple,
      StakeDepositedEvent.OutputTuple,
      StakeDepositedEvent.OutputObject
    >;

    "StakeWithdrawn(address,uint256,uint256)": TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;
    StakeWithdrawn: TypedContractEvent<
      StakeWithdrawnEvent.InputTuple,
      StakeWithdrawnEvent.OutputTuple,
      StakeWithdrawnEvent.OutputObject
    >;

    "ValidatorRewarded(address,uint256)": TypedContractEvent<
      ValidatorRewardedEvent.InputTuple,
      ValidatorRewardedEvent.OutputTuple,
      ValidatorRewardedEvent.OutputObject
    >;
    ValidatorRewarded: TypedContractEvent<
      ValidatorRewardedEvent.InputTuple,
      ValidatorRewardedEvent.OutputTuple,
      ValidatorRewardedEvent.OutputObject
    >;
  };
}
