/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace ValidatorRegistry {
  export type ValidatorStruct = {
    node: AddressLike;
    stake: BigNumberish;
    active: boolean;
    lastProof: BigNumberish;
  };

  export type ValidatorStructOutput = [
    node: string,
    stake: bigint,
    active: boolean,
    lastProof: bigint
  ] & { node: string; stake: bigint; active: boolean; lastProof: bigint };
}

export interface ValidatorRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivate"
      | "getActiveValidators"
      | "getValidator"
      | "owner"
      | "register"
      | "setStakingContract"
      | "stakingContract"
      | "updateLastProof"
      | "updateStake"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ProofTimestampUpdated"
      | "StakeUpdated"
      | "StakingContractSet"
      | "ValidatorDeactivated"
      | "ValidatorRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivate",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getActiveValidators",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getValidator",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "register", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setStakingContract",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stakingContract",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateLastProof",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStake",
    values: [AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "deactivate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActiveValidators",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getValidator",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "register", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setStakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "stakingContract",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateLastProof",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStake",
    data: BytesLike
  ): Result;
}

export namespace ProofTimestampUpdatedEvent {
  export type InputTuple = [node: AddressLike, lastProof: BigNumberish];
  export type OutputTuple = [node: string, lastProof: bigint];
  export interface OutputObject {
    node: string;
    lastProof: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakeUpdatedEvent {
  export type InputTuple = [node: AddressLike, newStake: BigNumberish];
  export type OutputTuple = [node: string, newStake: bigint];
  export interface OutputObject {
    node: string;
    newStake: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace StakingContractSetEvent {
  export type InputTuple = [stakingContract: AddressLike];
  export type OutputTuple = [stakingContract: string];
  export interface OutputObject {
    stakingContract: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorDeactivatedEvent {
  export type InputTuple = [node: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [node: string, timestamp: bigint];
  export interface OutputObject {
    node: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ValidatorRegisteredEvent {
  export type InputTuple = [node: AddressLike, timestamp: BigNumberish];
  export type OutputTuple = [node: string, timestamp: bigint];
  export interface OutputObject {
    node: string;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ValidatorRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): ValidatorRegistry;
  waitForDeployment(): Promise<this>;

  interface: ValidatorRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivate: TypedContractMethod<[], [void], "nonpayable">;

  getActiveValidators: TypedContractMethod<
    [],
    [ValidatorRegistry.ValidatorStructOutput[]],
    "view"
  >;

  getValidator: TypedContractMethod<
    [node: AddressLike],
    [ValidatorRegistry.ValidatorStructOutput],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  register: TypedContractMethod<[], [void], "nonpayable">;

  setStakingContract: TypedContractMethod<
    [_staking: AddressLike],
    [void],
    "nonpayable"
  >;

  stakingContract: TypedContractMethod<[], [string], "view">;

  updateLastProof: TypedContractMethod<
    [node: AddressLike, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateStake: TypedContractMethod<
    [node: AddressLike, newStake: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivate"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getActiveValidators"
  ): TypedContractMethod<
    [],
    [ValidatorRegistry.ValidatorStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getValidator"
  ): TypedContractMethod<
    [node: AddressLike],
    [ValidatorRegistry.ValidatorStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "register"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setStakingContract"
  ): TypedContractMethod<[_staking: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "stakingContract"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateLastProof"
  ): TypedContractMethod<
    [node: AddressLike, timestamp: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateStake"
  ): TypedContractMethod<
    [node: AddressLike, newStake: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ProofTimestampUpdated"
  ): TypedContractEvent<
    ProofTimestampUpdatedEvent.InputTuple,
    ProofTimestampUpdatedEvent.OutputTuple,
    ProofTimestampUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StakeUpdated"
  ): TypedContractEvent<
    StakeUpdatedEvent.InputTuple,
    StakeUpdatedEvent.OutputTuple,
    StakeUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "StakingContractSet"
  ): TypedContractEvent<
    StakingContractSetEvent.InputTuple,
    StakingContractSetEvent.OutputTuple,
    StakingContractSetEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorDeactivated"
  ): TypedContractEvent<
    ValidatorDeactivatedEvent.InputTuple,
    ValidatorDeactivatedEvent.OutputTuple,
    ValidatorDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "ValidatorRegistered"
  ): TypedContractEvent<
    ValidatorRegisteredEvent.InputTuple,
    ValidatorRegisteredEvent.OutputTuple,
    ValidatorRegisteredEvent.OutputObject
  >;

  filters: {
    "ProofTimestampUpdated(address,uint256)": TypedContractEvent<
      ProofTimestampUpdatedEvent.InputTuple,
      ProofTimestampUpdatedEvent.OutputTuple,
      ProofTimestampUpdatedEvent.OutputObject
    >;
    ProofTimestampUpdated: TypedContractEvent<
      ProofTimestampUpdatedEvent.InputTuple,
      ProofTimestampUpdatedEvent.OutputTuple,
      ProofTimestampUpdatedEvent.OutputObject
    >;

    "StakeUpdated(address,uint256)": TypedContractEvent<
      StakeUpdatedEvent.InputTuple,
      StakeUpdatedEvent.OutputTuple,
      StakeUpdatedEvent.OutputObject
    >;
    StakeUpdated: TypedContractEvent<
      StakeUpdatedEvent.InputTuple,
      StakeUpdatedEvent.OutputTuple,
      StakeUpdatedEvent.OutputObject
    >;

    "StakingContractSet(address)": TypedContractEvent<
      StakingContractSetEvent.InputTuple,
      StakingContractSetEvent.OutputTuple,
      StakingContractSetEvent.OutputObject
    >;
    StakingContractSet: TypedContractEvent<
      StakingContractSetEvent.InputTuple,
      StakingContractSetEvent.OutputTuple,
      StakingContractSetEvent.OutputObject
    >;

    "ValidatorDeactivated(address,uint256)": TypedContractEvent<
      ValidatorDeactivatedEvent.InputTuple,
      ValidatorDeactivatedEvent.OutputTuple,
      ValidatorDeactivatedEvent.OutputObject
    >;
    ValidatorDeactivated: TypedContractEvent<
      ValidatorDeactivatedEvent.InputTuple,
      ValidatorDeactivatedEvent.OutputTuple,
      ValidatorDeactivatedEvent.OutputObject
    >;

    "ValidatorRegistered(address,uint256)": TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;
    ValidatorRegistered: TypedContractEvent<
      ValidatorRegisteredEvent.InputTuple,
      ValidatorRegisteredEvent.OutputTuple,
      ValidatorRegisteredEvent.OutputObject
    >;
  };
}
