/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface DAOExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptAdmin"
      | "admin"
      | "cancelTransaction"
      | "delay"
      | "executeTransaction"
      | "minDelay"
      | "pendingAdmin"
      | "queueTransaction"
      | "setDelay"
      | "setPendingAdmin"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionCancelled"
      | "ActionExecuted"
      | "ActionQueued"
      | "NewAdmin"
      | "NewDelay"
      | "NewPendingAdmin"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "cancelTransaction",
    values: [BigNumberish, AddressLike, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "delay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish, AddressLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "minDelay", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "queueTransaction",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      string,
      BytesLike,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "setDelay",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setPendingAdmin",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "cancelTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "delay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "minDelay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setDelay", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPendingAdmin",
    data: BytesLike
  ): Result;
}

export namespace ActionCancelledEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    target: AddressLike,
    signature: string
  ];
  export type OutputTuple = [
    proposalId: bigint,
    target: string,
    signature: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    target: string;
    signature: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionExecutedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    target: AddressLike,
    value: BigNumberish,
    signature: string,
    data: BytesLike
  ];
  export type OutputTuple = [
    proposalId: bigint,
    target: string,
    value: bigint,
    signature: string,
    data: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    target: string;
    value: bigint;
    signature: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionQueuedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    target: AddressLike,
    value: BigNumberish,
    signature: string,
    data: BytesLike,
    eta: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    target: string,
    value: bigint,
    signature: string,
    data: string,
    eta: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    target: string;
    value: bigint;
    signature: string;
    data: string;
    eta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewAdminEvent {
  export type InputTuple = [oldAdmin: AddressLike, newAdmin: AddressLike];
  export type OutputTuple = [oldAdmin: string, newAdmin: string];
  export interface OutputObject {
    oldAdmin: string;
    newAdmin: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewDelayEvent {
  export type InputTuple = [oldDelay: BigNumberish, newDelay: BigNumberish];
  export type OutputTuple = [oldDelay: bigint, newDelay: bigint];
  export interface OutputObject {
    oldDelay: bigint;
    newDelay: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace NewPendingAdminEvent {
  export type InputTuple = [oldPending: AddressLike, newPending: AddressLike];
  export type OutputTuple = [oldPending: string, newPending: string];
  export interface OutputObject {
    oldPending: string;
    newPending: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DAOExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): DAOExecutor;
  waitForDeployment(): Promise<this>;

  interface: DAOExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptAdmin: TypedContractMethod<[], [void], "nonpayable">;

  admin: TypedContractMethod<[], [string], "view">;

  cancelTransaction: TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      signature: string,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  delay: TypedContractMethod<[], [bigint], "view">;

  executeTransaction: TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      signature: string,
      data: BytesLike
    ],
    [string],
    "payable"
  >;

  minDelay: TypedContractMethod<[], [bigint], "view">;

  pendingAdmin: TypedContractMethod<[], [string], "view">;

  queueTransaction: TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      eta: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  setDelay: TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;

  setPendingAdmin: TypedContractMethod<
    [newPending: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptAdmin"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cancelTransaction"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      signature: string,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "delay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      signature: string,
      data: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "minDelay"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "pendingAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "queueTransaction"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      eta: BigNumberish
    ],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setDelay"
  ): TypedContractMethod<[newDelay: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPendingAdmin"
  ): TypedContractMethod<[newPending: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ActionCancelled"
  ): TypedContractEvent<
    ActionCancelledEvent.InputTuple,
    ActionCancelledEvent.OutputTuple,
    ActionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ActionExecuted"
  ): TypedContractEvent<
    ActionExecutedEvent.InputTuple,
    ActionExecutedEvent.OutputTuple,
    ActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ActionQueued"
  ): TypedContractEvent<
    ActionQueuedEvent.InputTuple,
    ActionQueuedEvent.OutputTuple,
    ActionQueuedEvent.OutputObject
  >;
  getEvent(
    key: "NewAdmin"
  ): TypedContractEvent<
    NewAdminEvent.InputTuple,
    NewAdminEvent.OutputTuple,
    NewAdminEvent.OutputObject
  >;
  getEvent(
    key: "NewDelay"
  ): TypedContractEvent<
    NewDelayEvent.InputTuple,
    NewDelayEvent.OutputTuple,
    NewDelayEvent.OutputObject
  >;
  getEvent(
    key: "NewPendingAdmin"
  ): TypedContractEvent<
    NewPendingAdminEvent.InputTuple,
    NewPendingAdminEvent.OutputTuple,
    NewPendingAdminEvent.OutputObject
  >;

  filters: {
    "ActionCancelled(uint256,address,string)": TypedContractEvent<
      ActionCancelledEvent.InputTuple,
      ActionCancelledEvent.OutputTuple,
      ActionCancelledEvent.OutputObject
    >;
    ActionCancelled: TypedContractEvent<
      ActionCancelledEvent.InputTuple,
      ActionCancelledEvent.OutputTuple,
      ActionCancelledEvent.OutputObject
    >;

    "ActionExecuted(uint256,address,uint256,string,bytes)": TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;
    ActionExecuted: TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;

    "ActionQueued(uint256,address,uint256,string,bytes,uint256)": TypedContractEvent<
      ActionQueuedEvent.InputTuple,
      ActionQueuedEvent.OutputTuple,
      ActionQueuedEvent.OutputObject
    >;
    ActionQueued: TypedContractEvent<
      ActionQueuedEvent.InputTuple,
      ActionQueuedEvent.OutputTuple,
      ActionQueuedEvent.OutputObject
    >;

    "NewAdmin(address,address)": TypedContractEvent<
      NewAdminEvent.InputTuple,
      NewAdminEvent.OutputTuple,
      NewAdminEvent.OutputObject
    >;
    NewAdmin: TypedContractEvent<
      NewAdminEvent.InputTuple,
      NewAdminEvent.OutputTuple,
      NewAdminEvent.OutputObject
    >;

    "NewDelay(uint256,uint256)": TypedContractEvent<
      NewDelayEvent.InputTuple,
      NewDelayEvent.OutputTuple,
      NewDelayEvent.OutputObject
    >;
    NewDelay: TypedContractEvent<
      NewDelayEvent.InputTuple,
      NewDelayEvent.OutputTuple,
      NewDelayEvent.OutputObject
    >;

    "NewPendingAdmin(address,address)": TypedContractEvent<
      NewPendingAdminEvent.InputTuple,
      NewPendingAdminEvent.OutputTuple,
      NewPendingAdminEvent.OutputObject
    >;
    NewPendingAdmin: TypedContractEvent<
      NewPendingAdminEvent.InputTuple,
      NewPendingAdminEvent.OutputTuple,
      NewPendingAdminEvent.OutputObject
    >;
  };
}
