/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface TreasuryMockInterface extends Interface {
  getFunction(nameOrSignature: "requestWithdrawal"): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "MockDeposit" | "MockWithdrawalRequested"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "requestWithdrawal",
    values: [AddressLike, BigNumberish, string]
  ): string;

  decodeFunctionResult(
    functionFragment: "requestWithdrawal",
    data: BytesLike
  ): Result;
}

export namespace MockDepositEvent {
  export type InputTuple = [
    from: AddressLike,
    amount: BigNumberish,
    memo: string
  ];
  export type OutputTuple = [from: string, amount: bigint, memo: string];
  export interface OutputObject {
    from: string;
    amount: bigint;
    memo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MockWithdrawalRequestedEvent {
  export type InputTuple = [
    to: AddressLike,
    amount: BigNumberish,
    memo: string
  ];
  export type OutputTuple = [to: string, amount: bigint, memo: string];
  export interface OutputObject {
    to: string;
    amount: bigint;
    memo: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TreasuryMock extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryMock;
  waitForDeployment(): Promise<this>;

  interface: TreasuryMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  requestWithdrawal: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, memo: string],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "requestWithdrawal"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish, memo: string],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "MockDeposit"
  ): TypedContractEvent<
    MockDepositEvent.InputTuple,
    MockDepositEvent.OutputTuple,
    MockDepositEvent.OutputObject
  >;
  getEvent(
    key: "MockWithdrawalRequested"
  ): TypedContractEvent<
    MockWithdrawalRequestedEvent.InputTuple,
    MockWithdrawalRequestedEvent.OutputTuple,
    MockWithdrawalRequestedEvent.OutputObject
  >;

  filters: {
    "MockDeposit(address,uint256,string)": TypedContractEvent<
      MockDepositEvent.InputTuple,
      MockDepositEvent.OutputTuple,
      MockDepositEvent.OutputObject
    >;
    MockDeposit: TypedContractEvent<
      MockDepositEvent.InputTuple,
      MockDepositEvent.OutputTuple,
      MockDepositEvent.OutputObject
    >;

    "MockWithdrawalRequested(address,uint256,string)": TypedContractEvent<
      MockWithdrawalRequestedEvent.InputTuple,
      MockWithdrawalRequestedEvent.OutputTuple,
      MockWithdrawalRequestedEvent.OutputObject
    >;
    MockWithdrawalRequested: TypedContractEvent<
      MockWithdrawalRequestedEvent.InputTuple,
      MockWithdrawalRequestedEvent.OutputTuple,
      MockWithdrawalRequestedEvent.OutputObject
    >;
  };
}
