/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIndexFlowStaking,
  IIndexFlowStakingInterface,
} from "../../../src/interfaces/IIndexFlowStaking";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "account",
        type: "address",
      },
    ],
    name: "balances",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes32",
        name: "batchId",
        type: "bytes32",
      },
    ],
    name: "notifyReward",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "totalStaked",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IIndexFlowStaking__factory {
  static readonly abi = _abi;
  static createInterface(): IIndexFlowStakingInterface {
    return new Interface(_abi) as IIndexFlowStakingInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IIndexFlowStaking {
    return new Contract(address, _abi, runner) as unknown as IIndexFlowStaking;
  }
}
