/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface IDAOExecutorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "cancelTransaction"
      | "executeTransaction"
      | "queueTransaction"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ActionCancelled"
      | "ActionExecuted"
      | "ActionQueued"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "cancelTransaction",
    values: [BigNumberish, AddressLike, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTransaction",
    values: [BigNumberish, AddressLike, BigNumberish, string, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "queueTransaction",
    values: [
      BigNumberish,
      AddressLike,
      BigNumberish,
      string,
      BytesLike,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "cancelTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTransaction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "queueTransaction",
    data: BytesLike
  ): Result;
}

export namespace ActionCancelledEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    target: AddressLike,
    signature: string
  ];
  export type OutputTuple = [
    proposalId: bigint,
    target: string,
    signature: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    target: string;
    signature: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionExecutedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    target: AddressLike,
    value: BigNumberish,
    signature: string,
    data: BytesLike
  ];
  export type OutputTuple = [
    proposalId: bigint,
    target: string,
    value: bigint,
    signature: string,
    data: string
  ];
  export interface OutputObject {
    proposalId: bigint;
    target: string;
    value: bigint;
    signature: string;
    data: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ActionQueuedEvent {
  export type InputTuple = [
    proposalId: BigNumberish,
    target: AddressLike,
    value: BigNumberish,
    signature: string,
    data: BytesLike,
    eta: BigNumberish
  ];
  export type OutputTuple = [
    proposalId: bigint,
    target: string,
    value: bigint,
    signature: string,
    data: string,
    eta: bigint
  ];
  export interface OutputObject {
    proposalId: bigint;
    target: string;
    value: bigint;
    signature: string;
    data: string;
    eta: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IDAOExecutor extends BaseContract {
  connect(runner?: ContractRunner | null): IDAOExecutor;
  waitForDeployment(): Promise<this>;

  interface: IDAOExecutorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  cancelTransaction: TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      signature: string,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  executeTransaction: TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      signature: string,
      data: BytesLike
    ],
    [string],
    "payable"
  >;

  queueTransaction: TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      eta: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "cancelTransaction"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      signature: string,
      data: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "executeTransaction"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      signature: string,
      data: BytesLike
    ],
    [string],
    "payable"
  >;
  getFunction(
    nameOrSignature: "queueTransaction"
  ): TypedContractMethod<
    [
      proposalId: BigNumberish,
      target: AddressLike,
      value: BigNumberish,
      signature: string,
      data: BytesLike,
      eta: BigNumberish
    ],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "ActionCancelled"
  ): TypedContractEvent<
    ActionCancelledEvent.InputTuple,
    ActionCancelledEvent.OutputTuple,
    ActionCancelledEvent.OutputObject
  >;
  getEvent(
    key: "ActionExecuted"
  ): TypedContractEvent<
    ActionExecutedEvent.InputTuple,
    ActionExecutedEvent.OutputTuple,
    ActionExecutedEvent.OutputObject
  >;
  getEvent(
    key: "ActionQueued"
  ): TypedContractEvent<
    ActionQueuedEvent.InputTuple,
    ActionQueuedEvent.OutputTuple,
    ActionQueuedEvent.OutputObject
  >;

  filters: {
    "ActionCancelled(uint256,address,string)": TypedContractEvent<
      ActionCancelledEvent.InputTuple,
      ActionCancelledEvent.OutputTuple,
      ActionCancelledEvent.OutputObject
    >;
    ActionCancelled: TypedContractEvent<
      ActionCancelledEvent.InputTuple,
      ActionCancelledEvent.OutputTuple,
      ActionCancelledEvent.OutputObject
    >;

    "ActionExecuted(uint256,address,uint256,string,bytes)": TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;
    ActionExecuted: TypedContractEvent<
      ActionExecutedEvent.InputTuple,
      ActionExecutedEvent.OutputTuple,
      ActionExecutedEvent.OutputObject
    >;

    "ActionQueued(uint256,address,uint256,string,bytes,uint256)": TypedContractEvent<
      ActionQueuedEvent.InputTuple,
      ActionQueuedEvent.OutputTuple,
      ActionQueuedEvent.OutputObject
    >;
    ActionQueued: TypedContractEvent<
      ActionQueuedEvent.InputTuple,
      ActionQueuedEvent.OutputTuple,
      ActionQueuedEvent.OutputObject
    >;
  };
}
