/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../common";
import type { TreasuryMock, TreasuryMockInterface } from "../TreasuryMock";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "memo",
        type: "string",
      },
    ],
    name: "MockDeposit",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        indexed: false,
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        indexed: false,
        internalType: "string",
        name: "memo",
        type: "string",
      },
    ],
    name: "MockWithdrawalRequested",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "string",
        name: "memo",
        type: "string",
      },
    ],
    name: "requestWithdrawal",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506102a1806100206000396000f3fe6080604052600436106100225760003560e01c8063bebc3bfb146100f157600080fd5b366100ec57336001600160a01b03167f14cc3ca05aeb86b3db23d9ca7017cd780ff4d436b4cfded2bdf021cb23e9bc18346040516100979181526040602082018190526018908201527f4472792d72756e206465706f7369742064657465637465640000000000000000606082015260800190565b60405180910390a260405162461bcd60e51b815260206004820181905260248201527f54726561737572794d6f636b3a2076616c7565206e6f7420616363657074656460448201526064015b60405180910390fd5b600080fd5b3480156100fd57600080fd5b5061011161010c3660046101a0565b610113565b005b836001600160a01b03167fade695ca38940ce96229b6ed8915351896085f33f56d107dbbd984b0216c19e884848460405161015093929190610235565b60405180910390a260405162461bcd60e51b815260206004820152601a60248201527f54726561737572794d6f636b3a206472792d72756e206f6e6c7900000000000060448201526064016100e3565b600080600080606085870312156101b657600080fd5b84356001600160a01b03811681146101cd57600080fd5b935060208501359250604085013567ffffffffffffffff808211156101f157600080fd5b818701915087601f83011261020557600080fd5b81358181111561021457600080fd5b88602082850101111561022657600080fd5b95989497505060200194505050565b83815260406020820152816040820152818360608301376000818301606090810191909152601f909201601f191601019291505056fea2646970667358221220b6e29707ae111f4bedfed6caca4287c5c2006386e2e59a6895363a7d8ea6cbb364736f6c63430008180033";

type TreasuryMockConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: TreasuryMockConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class TreasuryMock__factory extends ContractFactory {
  constructor(...args: TreasuryMockConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      TreasuryMock & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): TreasuryMock__factory {
    return super.connect(runner) as TreasuryMock__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): TreasuryMockInterface {
    return new Interface(_abi) as TreasuryMockInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): TreasuryMock {
    return new Contract(address, _abi, runner) as unknown as TreasuryMock;
  }
}
